### ISSUE TITLE
can't find external program "pwsh"

### ISSUE THREAD

**Issue by jwdinkel** [ebekker/terraform-aws-cached-ami#1]
Hello,

Was looking for a simple module to find the latest windows 2012 base image for each region.
Can you help me with this? Taking the sample here and running it using cmder on windows...

In my folder I have just the two .tf files from sample and I have edited the source path to be 
source   = "ebekker/cached-ami/aws"

λ terraform init
Initializing modules...
- module.ami_win2016base
- module.ami_nat

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "null" (1.0.0)...
- Downloading plugin for provider "aws" (1.15.0)...
- Downloading plugin for provider "external" (1.0.0)...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.aws: version = "~> 1.15"
* provider.external: version = "~> 1.0"
* provider.null: version = "~> 1.0"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Here is the output:

> λ terraform apply
> data.external.item_cache: Refreshing state...
> data.external.item_cache: Refreshing state...
> 
> Error: Error refreshing state: 2 error(s) occurred:
> 
> * module.ami_win2016base.data.external.item_cache: 1 error(s) occurred:
> 
> * module.ami_win2016base.data.external.item_cache: data.external.item_cache: can't find external program "pwsh"
> * module.ami_nat.data.external.item_cache: 1 error(s) occurred:
> 
> * module.ami_nat.data.external.item_cache: data.external.item_cache: can't find external program "pwsh"

**Comment by ebekker** [comment]
I rely on PowerShell Core to implement the local scripting logic to store and read cached data locally.  Have you installed PowerShell Core to your local machine?

Also, you'll need to put the install location of PowerShell Core in your PATH so that simply invoking `pwsh` from a command prompt on Windows (or terminal console in non-Windows) will invoke the PowerShell Core shell.

**Comment by ebekker** [comment]
Hopefully your situation is resolved, reopen and comment if not.
